[package]
name = "rust_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"

thread_local = "1.1.4"
parking_lot = "0.12.1"
futures = "0.3.25"

[dependencies.tokio]
version = "1.22.0"
features = ["full"]

[dependencies.async-std]
version = "1.6"
features = ["attributes"]
