[package]
name = "rust_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thread_local = "1.1"
parking_lot = "0.12"
tokio = "1.22.0"
futures = "0.3"

lazy_static = "1.4.0"

[dependencies.async-std]
version = "1.6"
features = ["attributes"]
